vim.keymap.set("n", "<Leader>b", require("dap").toggle_breakpoint, { desc = "toggle [b]reakpoing" })
vim.keymap.set("n", "<leader>de", require("dap").close, { desc = "[e]nd debugging session" })
vim.keymap.set("n", "<Leader>dR", require("dap").restart, { desc = "dap [R]estart" })
vim.keymap.set("n", "<Leader>dc", require("dap").run_to_cursor, { desc = "run to [c]ursor" })
vim.keymap.set("n", "<Leader>dC", require("dap").continue, { desc = "[C]ontinue" })

vim.keymap.set("n", "<right>", require("dap").step_over, { desc = "step over" })
vim.keymap.set("n", "<down>", require("dap").step_into, { desc = "step into" })
vim.keymap.set("n", "<up>", require("dap").step_out, { desc = "step out" })
vim.keymap.set("n", "<left>", require("dap").step_back, { desc = "step out" })

vim.keymap.set("n", "<Leader>da", require("dap-view").add_expr, { desc = "[a]dd watching variable" })
vim.keymap.set("n", "<leader>du", require("dap-view").toggle, { desc = "dap[u]i toogle" })

-- sections = { "watches", "scopes", "exceptions", "breakpoints", "threads", "repl" },
vim.keymap.set("n", "<Leader>dw", function()
    require("dap-view").jump_to_view("watches")
end, { desc = "open watches" })
vim.keymap.set("n", "<Leader>ds", function()
    require("dap-view").jump_to_view("scopes")
end, { desc = "open scopes" })
vim.keymap.set("n", "<Leader>db", function()
    require("dap-view").jump_to_view("breakpoints")
end, { desc = "open breakpoints" })
vim.keymap.set("n", "<Leader>dt", function()
    require("dap-view").jump_to_view("threads")
end, { desc = "open threads" })
vim.keymap.set("n", "<Leader>dr", function()
    require("dap-view").jump_to_view("repl")
end, { desc = "open repl" })
